In [6]:
%load_ext autoreload
%autoreload 2
# Path setup
import sys
import os
path_to_vape = os.path.expanduser('~/Documents/code/Vape')
sys.path.append(path_to_vape)
sys.path.append(os.path.join(path_to_vape, 'jupyter'))
sys.path.append(os.path.join(path_to_vape, 'utils'))

# Folder containing mice folders with individual run pkls
pkl_path = '/home/jrowland/Documents/code/Vape/run_pkls'

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
import utils_funcs as utils
import run_functions as rf
from subsets_analysis import Subsets
import pickle
import sklearn.decomposition
from cycler import cycler
from Session import Session  # class that holds all data per session
plt.rcParams['axes.prop_cycle'] = cycler(color=sns.color_palette('colorblind'))

In [8]:
### DO YOU WANT TO USE SPKS INSTEAD OF FLU
use_spks = True

In [9]:
## Load data
sessions = {}

def only_numerics(seq):
    seq_type= type(seq)
    return seq_type().join(filter(seq_type.isdigit, seq))

def load_files(save_dict, data_dict, folder_path):
    total_ds = 0
    for mouse in data_dict.keys():
        for run_number in data_dict[mouse]:
            try:  # try/except framework to filter datasets that don't work - for whatever reason
                save_dict[total_ds] = Session(mouse, run_number, folder_path, pre_gap_seconds=0,
                                              post_gap_seconds=0, post_seconds=8, use_spks=use_spks)
                total_ds += 1
                print(f'succesfully loaded mouse {mouse}, run {run_number}')
            except AttributeError:
                pass
#                 print(f'error in mouse {mouse}, run {run_number}')
    return save_dict, total_ds


## Select all possible mouse/run combos:
# pkl_path = '/mnt/qnap_jrowland/run_pkls'
# all_mice = [x for x in os.listdir(pkl_path) if x[-4:] != '.pkl']
# run_dict = {m: list(np.unique([int(only_numerics(x)) for x in os.listdir(pkl_path + f'/{m}')])) for m in all_mice}
# run_dict = {'J064' : [10],
#             'RL048': [23]}
# sessions, total_ds = load_files(save_dict=sessions, data_dict=run_dict, folder_path=pkl_path)

all_mice = [x for x in os.listdir(pkl_path) if x[-4:] != '.pkl']
# all_mice = ['J048', 'RL048']
run_dict = {m: list(np.unique([int(only_numerics(x)) for x in os.listdir(pkl_path + f'/{m}')])) for m in all_mice}
#run_dict = {'J048': [27], 'RL070': [28, 29]}
#run_dict = {'RL070': [29]}

if 'J065' in run_dict.keys() and 14 in run_dict['J065']:
    run_dict['J065'].remove(14)
# del run_dict['J048']
# del run_dict['RL048']
sessions, total_ds = load_files(save_dict=sessions, data_dict=run_dict, folder_path=pkl_path)
     
print('The following sessions were loaded:')
for _, ss in sessions.items():
    print(ss, '- frequency:', ss.frequency)

Now loading mouse RL070, run 22
Now loading mouse RL070, run 23
Now loading mouse RL070, run 24
Now loading mouse RL070, run 27
Now loading mouse RL070, run 28


  0%|          | 0/625 [00:00<?, ?it/s]

microcontroller trial starts occur on average -70.14 ms from galvo trial starts


100%|██████████| 625/625 [04:49<00:00,  2.16it/s]


0 / 625 cells filtered
photo stim occurences: {0: 127, 1: 140, 2: 119}
Occurence table:
[[123.   4.]
 [119.  21.]
 [ 80.  39.]]
373 / 373 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse RL070, run 28
Now loading mouse RL070, run 29


  0%|          | 0/718 [00:00<?, ?it/s]

microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 718/718 [03:59<00:00,  3.00it/s]


0 / 718 cells filtered
photo stim occurences: {0: 96, 1: 93, 2: 90}
Occurence table:
[[78. 18.]
 [46. 47.]
 [35. 55.]]
261 / 261 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse RL070, run 29
Now loading mouse J047, run 7
Now loading mouse J048, run 15
Now loading mouse J048, run 16
Now loading mouse J048, run 18
Now loading mouse J048, run 19
Now loading mouse J048, run 26
Now loading mouse J048, run 27


  0%|          | 3/2101 [00:00<01:21, 25.77it/s]

microcontroller trial starts occur on average -73.26 ms from galvo trial starts


100%|██████████| 2101/2101 [01:10<00:00, 29.67it/s]


0 / 2101 cells filtered
photo stim occurences: {0: 51, 1: 51, 2: 41}
Occurence table:
[[26. 25.]
 [25. 26.]
 [ 5. 36.]]
130 / 130 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J048, run 27
Now loading mouse J048, run 28


  0%|          | 2/2194 [00:00<02:12, 16.58it/s]

microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 2194/2194 [01:24<00:00, 25.82it/s]


0 / 2194 cells filtered
photo stim occurences: {0: 60, 1: 58, 2: 55}
Occurence table:
[[43. 17.]
 [24. 34.]
 [19. 36.]]
160 / 160 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J048, run 28
Now loading mouse J048, run 29


  0%|          | 0/1531 [00:00<?, ?it/s]

microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 1531/1531 [02:49<00:00,  9.03it/s]


0 / 1531 cells filtered
photo stim occurences: {0: 127, 1: 138, 2: 113}
Occurence table:
[[73. 54.]
 [59. 79.]
 [30. 83.]]
303 / 303 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J048, run 29
Now loading mouse J048, run 30


  0%|          | 0/2085 [00:00<?, ?it/s]

microcontroller trial starts occur on average -69.58 ms from galvo trial starts


100%|██████████| 2085/2085 [02:33<00:00, 13.56it/s]


0 / 2085 cells filtered
photo stim occurences: {0: 88, 1: 84, 2: 63}
Occurence table:
[[56. 32.]
 [31. 53.]
 [ 9. 54.]]
208 / 208 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J048, run 30
Now loading mouse J048, run 31
Now loading mouse J048, run 32


  0%|          | 0/1972 [00:00<?, ?it/s]

microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 1972/1972 [03:12<00:00, 10.24it/s]


0 / 1972 cells filtered
photo stim occurences: {0: 94, 1: 82, 2: 98}
Occurence table:
[[67. 27.]
 [42. 40.]
 [31. 67.]]
254 / 254 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J048, run 32
Now loading mouse RL022, run 5
Now loading mouse RL022, run 7
Now loading mouse RL022, run 11
Now loading mouse RL022, run 13
Now loading mouse RL022, run 14
Now loading mouse J064, run 10


  0%|          | 0/477 [00:00<?, ?it/s]

microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 477/477 [04:41<00:00,  1.69it/s]


0 / 477 cells filtered
photo stim occurences: {0: 66, 1: 58, 2: 49}
Occurence table:
[[38. 28.]
 [20. 38.]
 [ 6. 43.]]
162 / 162 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J064, run 10
Now loading mouse J064, run 11
microcontroller trial starts occur on average -52.47 ms from galvo trial starts


100%|██████████| 802/802 [06:33<00:00,  2.04it/s]


0 / 802 cells filtered
photo stim occurences: {0: 46, 1: 66, 2: 64}
Occurence table:
[[33. 13.]
 [26. 40.]
 [ 8. 56.]]
167 / 167 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J064, run 11
Now loading mouse J064, run 12
Now loading mouse J064, run 13
Now loading mouse J064, run 14
microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 981/981 [10:56<00:00,  1.49it/s]


0 / 981 cells filtered
photo stim occurences: {0: 63, 1: 82, 2: 76}
Occurence table:
[[37. 26.]
 [30. 52.]
 [ 9. 67.]]
208 / 208 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J064, run 14
Now loading mouse J064, run 15
Now loading mouse RL072, run 19
Now loading mouse RL072, run 20
Now loading mouse RL072, run 21
Now loading mouse RL072, run 24
Now loading mouse J063, run 8


  0%|          | 0/160 [00:00<?, ?it/s]

microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 160/160 [00:39<00:00,  4.05it/s]


0 / 160 cells filtered
photo stim occurences: {0: 63, 1: 66, 2: 61}
Occurence table:
[[51. 12.]
 [48. 18.]
 [14. 47.]]
113 / 113 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J063, run 8
Now loading mouse J063, run 9
microcontroller trial starts occur on average -71.64 ms from galvo trial starts


100%|██████████| 760/760 [06:44<00:00,  1.88it/s]


0 / 760 cells filtered
photo stim occurences: {0: 66, 1: 76, 2: 78}
Occurence table:
[[46. 20.]
 [47. 29.]
 [ 9. 69.]]
209 / 209 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J063, run 9
Now loading mouse J063, run 10
Now loading mouse J063, run 11
Now loading mouse J063, run 12
Now loading mouse J063, run 13
Now loading mouse J063, run 14
Now loading mouse RL023, run 5
Now loading mouse RL023, run 7
Now loading mouse RL023, run 8
Now loading mouse RL023, run 9
Now loading mouse RL023, run 11
Now loading mouse RL023, run 12
Now loading mouse RL048, run 14
Now loading mouse RL048, run 23


  0%|          | 0/3571 [00:00<?, ?it/s]

microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 3571/3571 [01:37<00:00, 36.45it/s]


0 / 3571 cells filtered
photo stim occurences: {0: 62, 1: 52, 2: 56}
Occurence table:
[[56.  6.]
 [36. 16.]
 [20. 36.]]
140 / 140 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40 150]
succesfully loaded mouse RL048, run 23
Now loading mouse RL048, run 24
microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 3063/3063 [02:02<00:00, 24.94it/s]


0 / 3063 cells filtered
photo stim occurences: {0: 74, 1: 74, 2: 75}
Occurence table:
[[69.  5.]
 [51. 23.]
 [29. 46.]]
151 / 151 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse RL048, run 24
Now loading mouse RL048, run 25
microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 2892/2892 [03:14<00:00, 14.83it/s]


0 / 2892 cells filtered
photo stim occurences: {0: 164, 1: 135, 2: 144}
Occurence table:
[[151.  13.]
 [112.  23.]
 [ 90.  54.]]
385 / 385 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse RL048, run 25
Now loading mouse RL048, run 28
microcontroller trial starts occur on average -59.85 ms from galvo trial starts


100%|██████████| 2727/2727 [02:31<00:00, 17.95it/s]


0 / 2727 cells filtered
photo stim occurences: {0: 120, 1: 113, 2: 108}
Occurence table:
[[117.   3.]
 [105.   8.]
 [ 75.  33.]]
328 / 328 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse RL048, run 28
Now loading mouse RL048, run 29
microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 1992/1992 [01:24<00:00, 23.48it/s]


0 / 1992 cells filtered
photo stim occurences: {0: 75, 1: 89, 2: 92}
Occurence table:
[[71.  4.]
 [85.  4.]
 [61. 31.]]
245 / 245 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse RL048, run 29
Now loading mouse RL032, run 7
Now loading mouse RL032, run 10
Now loading mouse RL032, run 12
Now loading mouse RL032, run 13
Now loading mouse J065, run 10
microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 131/131 [01:36<00:00,  1.35it/s]


0 / 131 cells filtered
photo stim occurences: {0: 67, 1: 75, 2: 69}
Occurence table:
[[38. 29.]
 [23. 52.]
 [ 4. 65.]]
197 / 197 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J065, run 10
Now loading mouse J065, run 11
microcontroller trial starts occur on average nan ms from galvo trial starts


100%|██████████| 410/410 [03:47<00:00,  1.80it/s]


0 / 410 cells filtered
photo stim occurences: {0: 64, 1: 65, 2: 75}
Occurence table:
[[23. 41.]
 [18. 47.]
 [ 9. 66.]]
195 / 195 non nan trials identified
Numbers of PS cells: [  0   5  10  20  30  40  50 150]
succesfully loaded mouse J065, run 11
Now loading mouse J065, run 12
Now loading mouse J065, run 13
Now loading mouse J065, run 15
The following sessions were loaded:
Mouse RL070, run 28 - frequency: 30
Mouse RL070, run 29 - frequency: 30
Mouse J048, run 27 - frequency: 5
Mouse J048, run 28 - frequency: 5
Mouse J048, run 29 - frequency: 5
Mouse J048, run 30 - frequency: 5
Mouse J048, run 32 - frequency: 5
Mouse J064, run 10 - frequency: 30
Mouse J064, run 11 - frequency: 30
Mouse J064, run 14 - frequency: 30
Mouse J063, run 8 - frequency: 30
Mouse J063, run 9 - frequency: 30
Mouse RL048, run 23 - frequency: 5
Mouse RL048, run 24 - frequency: 5
Mouse RL048, run 25 - frequency: 5
Mouse RL048, run 28 - frequency: 5
Mouse RL048, run 29 - frequency: 5
Mouse J065, run 10 - frequency: 3

In [16]:
sessions_path = os.path.expanduser('~/mnt/qnap/session_pkls')


for idx, session in sessions.items():
    
    if use_spks:
        file_name = 'session{}_spks.pkl'.format(idx)
    else:
        file_name = 'session{}.pkl'.format(idx)
    
    file_path = os.path.join(sessions_path, file_name)
    
    with open(file_path, 'wb') as f:
        pickle.dump(session, f, pickle.HIGHEST_PROTOCOL)

In [13]:
sessions_path

'/home/jrowland/mnt/qnap/Data/sessions_spks.pkl'

In [ ]:
Session?


In [ ]:
27130656 / 1e9